version: '2.1'

services:
  mysql:
    image: mysql:${MYSQL_VERSION:-5}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-dangerous}
    volumes:
    - 'mysql_data:/var/lib/mysql'
    - './setup.sql:/docker-entrypoint-initdb.d/00-setup.sql:ro'
    ports:
    - '3306:3306'
    healthcheck:
      test: mysql -uroot -p${MYSQL_ROOT_PASSWORD:-dangerous} -hlocalhost -e 'select 1' tictactoe
      timeout: '10s'
      retries: '5'

  game:
    build:
      context: .
    working_dir: '/usr/src/app'
    command: 'python server.py'
    volumes:
    - '.:/usr/src/app'
    - './db.docker.cnf:/usr/src/app/db.local.cnf'
    depends_on:
      mysql:
        condition: 'service_healthy'
    links:
    - 'mysql'
    ports:
    - ${GAME_PORT:-80}:5000

volumes:
  mysql_data: {}

